# Generated by Django 3.0.6 on 2020-05-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toy',
            old_name='descriptions',
            new_name='description',
        ),
    ]
