# Generated by Django 3.0.6 on 2020-05-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_auto_20200518_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toy',
            old_name='tou_category',
            new_name='toy_category',
        ),
    ]
